spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ycwmuyi/SpringCloudLearnConfig.git
#          仓库的路径
          search-paths: spring_cloud_config
#          公开仓库用户名和密码可以不写
          username:
          passphrase:
#          仓库的分支
      label: master

server:
  port: 8888


